feat(Conductor): notify Conductor of new users via webhook
LibreTexts/LibreOne pull request #46
Opened 2023-12-06 23:44 UTC by jakeaturner

Requires two new environment variables:

1. CONDUCTOR_WEBHOOK_BASE=https://commons.libretexts.org/api/v1/central-identity/webhooks
2. CONDUCTOR_API_KEY=

2023-12-27 05:04 UTC, ethanaturner requested changes
see one change, otherwise LGTM

2023-12-27 05:04 UTC, ethanaturner commented on server/controllers/AuthController.ts
> +      const res = await fetch(conductorWebhookURL, {
convert to axios

2023-12-30 05:21 UTC, jakeaturner commented
ENV config updated

2023-12-30 20:20 UTC, ethanaturner requested changes

2023-12-30 20:20 UTC, ethanaturner commented on server/controllers/UserController.ts
> -  public async getUserLibraryAppSandboxURL(req: Request, res: Response): Promise<Response> {
Keep this until we fully deprecate sandboxes

2023-12-30 20:20 UTC, ethanaturner commented on server/models/UserApplication.ts
> -  @Column(DataType.STRING)
Keep this until we fully deprecate sandboxes

2023-12-30 20:20 UTC, ethanaturner commented on server/controllers/LibraryController.ts
> -  public async getLibraryUserSandboxURL(lib: string, uuid: string) {
Keep this until we fully deprecate sandboxes

2023-12-30 20:20 UTC, ethanaturner commented on server/controllers/LibraryController.ts
> -  public async createLibraryUserSandbox(lib: string, libUserID: string, userData: CreateLibraryUserSandboxUserDataInput, headers?: LibraryAPIRequestHeaders) {
Double-check that there are no other calls to this function (e.g. an API route)

2023-12-31 02:45 UTC, ethanaturner approved these changes
_ET_. 12/30/23.

2024-01-11 17:15 UTC, merged